// PM2 Ecosystem Configuration for Magnus Flipper AI
// Run with: pm2 start ecosystem.config.js

module.exports = {
  apps: [
    {
      name: 'scheduler',
      script: 'apps/scheduler/src/index.js',
      cwd: '/Users/chinyeosemene/Developer/Magnus-Flipper-AI-v1.0-pro',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        REDIS_HOST: process.env.REDIS_HOST || 'localhost',
        REDIS_PORT: process.env.REDIS_PORT || '6379',
        POSTGRES_HOST: process.env.POSTGRES_HOST || 'localhost',
        POSTGRES_PORT: process.env.POSTGRES_PORT || '5432',
        POSTGRES_DB: process.env.POSTGRES_DB || 'sniper_db',
        POSTGRES_USER: process.env.POSTGRES_USER || 'user',
        POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD || 'password',
      },
      error_file: './logs/scheduler-error.log',
      out_file: './logs/scheduler-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'worker-crawler',
      script: 'apps/worker-crawler/src/index.js',
      cwd: '/Users/chinyeosemene/Developer/Magnus-Flipper-AI-v1.0-pro',
      instances: 2,
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        REDIS_HOST: process.env.REDIS_HOST || 'localhost',
        REDIS_PORT: process.env.REDIS_PORT || '6379',
      },
      error_file: './logs/worker-crawler-error.log',
      out_file: './logs/worker-crawler-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'worker-analyzer',
      script: 'apps/worker-analyzer/src/index.js',
      cwd: '/Users/chinyeosemene/Developer/Magnus-Flipper-AI-v1.0-pro',
      instances: 2,
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      env: {
        NODE_ENV: 'production',
        REDIS_HOST: process.env.REDIS_HOST || 'localhost',
        REDIS_PORT: process.env.REDIS_PORT || '6379',
        POSTGRES_HOST: process.env.POSTGRES_HOST || 'localhost',
        POSTGRES_PORT: process.env.POSTGRES_PORT || '5432',
        POSTGRES_DB: process.env.POSTGRES_DB || 'sniper_db',
        POSTGRES_USER: process.env.POSTGRES_USER || 'user',
        POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD || 'password',
      },
      error_file: './logs/worker-analyzer-error.log',
      out_file: './logs/worker-analyzer-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'worker-alerts',
      script: 'apps/worker-alerts/src/index.js',
      cwd: '/Users/chinyeosemene/Developer/Magnus-Flipper-AI-v1.0-pro',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        REDIS_HOST: process.env.REDIS_HOST || 'localhost',
        REDIS_PORT: process.env.REDIS_PORT || '6379',
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
        TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
        TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
        SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
      },
      error_file: './logs/worker-alerts-error.log',
      out_file: './logs/worker-alerts-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'bot-telegram',
      script: 'apps/bot-telegram/src/index.ts',
      cwd: '/Users/chinyeosemene/Developer/Magnus-Flipper-AI-v1.0-pro',
      interpreter: 'node',
      interpreter_args: '--loader ts-node/esm',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
        API_URL: process.env.API_URL || 'http://localhost:4000',
      },
      error_file: './logs/bot-telegram-error.log',
      out_file: './logs/bot-telegram-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'api',
      script: 'packages/api/dist/server.js',
      cwd: '/Users/chinyeosemene/Developer/Magnus-Flipper-AI-v1.0-pro',
      instances: 2,
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 4000,
        REDIS_HOST: process.env.REDIS_HOST || 'localhost',
        REDIS_PORT: process.env.REDIS_PORT || '6379',
        SUPABASE_URL: process.env.SUPABASE_URL,
        SUPABASE_SERVICE_KEY: process.env.SUPABASE_SERVICE_KEY,
      },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'health-checker',
      script: 'pnpm',
      args: 'start --filter @magnus-flipper-ai/health-checker',
      cwd: '/Users/chinyeosemene/Developer/Magnus-Flipper-AI-v1.0-pro',
      env: {
        NODE_ENV: 'production',
        MAGNUS_WEB_URL: 'https://your-vercel-url-here.vercel.app',
        MAGNUS_API_URL: 'https://your-render-api-here.onrender.com/health',
      },
    },
  ],
};
