/**
 * Unified Scraped Listing Schema
 * All marketplace scrapers must output this format
 */
import { z } from "zod";
export declare const ScrapedListingSchema: z.ZodObject<{
    title: z.ZodString;
    price: z.ZodNumber;
    currency: z.ZodDefault<z.ZodString>;
    link: z.ZodString;
    images: z.ZodArray<z.ZodString, "many">;
    seller_id: z.ZodString;
    seller_name: z.ZodOptional<z.ZodString>;
    seller_rating: z.ZodOptional<z.ZodNumber>;
    seller_reviews_count: z.ZodOptional<z.ZodNumber>;
    timestamp: z.ZodString;
    location: z.ZodOptional<z.ZodString>;
    condition: z.ZodDefault<z.ZodEnum<["new", "like_new", "good", "fair", "poor", "unknown"]>>;
    category: z.ZodOptional<z.ZodString>;
    marketplace: z.ZodEnum<["facebook", "gumtree", "craigslist", "ebay", "vinted", "depop"]>;
    description: z.ZodOptional<z.ZodString>;
    shipping_available: z.ZodOptional<z.ZodBoolean>;
    shipping_cost: z.ZodOptional<z.ZodNumber>;
    views_count: z.ZodOptional<z.ZodNumber>;
    raw_data: z.ZodOptional<z.ZodAny>;
}, "strip", z.ZodTypeAny, {
    timestamp: string;
    currency: string;
    marketplace: "ebay" | "facebook" | "craigslist" | "vinted" | "gumtree" | "depop";
    link: string;
    title: string;
    price: number;
    images: string[];
    seller_id: string;
    condition: "unknown" | "new" | "like_new" | "good" | "fair" | "poor";
    description?: string | undefined;
    category?: string | undefined;
    seller_name?: string | undefined;
    seller_rating?: number | undefined;
    seller_reviews_count?: number | undefined;
    location?: string | undefined;
    shipping_available?: boolean | undefined;
    shipping_cost?: number | undefined;
    views_count?: number | undefined;
    raw_data?: any;
}, {
    timestamp: string;
    marketplace: "ebay" | "facebook" | "craigslist" | "vinted" | "gumtree" | "depop";
    link: string;
    title: string;
    price: number;
    images: string[];
    seller_id: string;
    description?: string | undefined;
    category?: string | undefined;
    currency?: string | undefined;
    seller_name?: string | undefined;
    seller_rating?: number | undefined;
    seller_reviews_count?: number | undefined;
    location?: string | undefined;
    condition?: "unknown" | "new" | "like_new" | "good" | "fair" | "poor" | undefined;
    shipping_available?: boolean | undefined;
    shipping_cost?: number | undefined;
    views_count?: number | undefined;
    raw_data?: any;
}>;
export type ScrapedListing = z.infer<typeof ScrapedListingSchema>;
export declare const NormalizedListingSchema: z.ZodObject<{
    title: z.ZodString;
    price: z.ZodNumber;
    currency: z.ZodDefault<z.ZodString>;
    link: z.ZodString;
    images: z.ZodArray<z.ZodString, "many">;
    seller_id: z.ZodString;
    seller_name: z.ZodOptional<z.ZodString>;
    seller_rating: z.ZodOptional<z.ZodNumber>;
    seller_reviews_count: z.ZodOptional<z.ZodNumber>;
    timestamp: z.ZodString;
    location: z.ZodOptional<z.ZodString>;
    condition: z.ZodDefault<z.ZodEnum<["new", "like_new", "good", "fair", "poor", "unknown"]>>;
    category: z.ZodOptional<z.ZodString>;
    marketplace: z.ZodEnum<["facebook", "gumtree", "craigslist", "ebay", "vinted", "depop"]>;
    description: z.ZodOptional<z.ZodString>;
    shipping_available: z.ZodOptional<z.ZodBoolean>;
    shipping_cost: z.ZodOptional<z.ZodNumber>;
    views_count: z.ZodOptional<z.ZodNumber>;
    raw_data: z.ZodOptional<z.ZodAny>;
} & {
    normalized_title: z.ZodString;
    normalized_price: z.ZodNumber;
    normalized_condition: z.ZodString;
    content_hash: z.ZodString;
    duplicate_group_id: z.ZodOptional<z.ZodString>;
    freshness_score: z.ZodNumber;
    first_seen_at: z.ZodString;
    last_seen_at: z.ZodString;
    is_anomaly: z.ZodDefault<z.ZodBoolean>;
    anomaly_reason: z.ZodOptional<z.ZodString>;
    anomaly_score: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    timestamp: string;
    currency: string;
    marketplace: "ebay" | "facebook" | "craigslist" | "vinted" | "gumtree" | "depop";
    link: string;
    title: string;
    price: number;
    images: string[];
    seller_id: string;
    condition: "unknown" | "new" | "like_new" | "good" | "fair" | "poor";
    normalized_title: string;
    normalized_price: number;
    normalized_condition: string;
    content_hash: string;
    freshness_score: number;
    first_seen_at: string;
    last_seen_at: string;
    is_anomaly: boolean;
    description?: string | undefined;
    category?: string | undefined;
    seller_name?: string | undefined;
    seller_rating?: number | undefined;
    seller_reviews_count?: number | undefined;
    location?: string | undefined;
    shipping_available?: boolean | undefined;
    shipping_cost?: number | undefined;
    views_count?: number | undefined;
    raw_data?: any;
    duplicate_group_id?: string | undefined;
    anomaly_reason?: string | undefined;
    anomaly_score?: number | undefined;
}, {
    timestamp: string;
    marketplace: "ebay" | "facebook" | "craigslist" | "vinted" | "gumtree" | "depop";
    link: string;
    title: string;
    price: number;
    images: string[];
    seller_id: string;
    normalized_title: string;
    normalized_price: number;
    normalized_condition: string;
    content_hash: string;
    freshness_score: number;
    first_seen_at: string;
    last_seen_at: string;
    description?: string | undefined;
    category?: string | undefined;
    currency?: string | undefined;
    seller_name?: string | undefined;
    seller_rating?: number | undefined;
    seller_reviews_count?: number | undefined;
    location?: string | undefined;
    condition?: "unknown" | "new" | "like_new" | "good" | "fair" | "poor" | undefined;
    shipping_available?: boolean | undefined;
    shipping_cost?: number | undefined;
    views_count?: number | undefined;
    raw_data?: any;
    duplicate_group_id?: string | undefined;
    is_anomaly?: boolean | undefined;
    anomaly_reason?: string | undefined;
    anomaly_score?: number | undefined;
}>;
export type NormalizedListing = z.infer<typeof NormalizedListingSchema>;
export interface ScraperConfig {
    marketplace: string;
    enabled: boolean;
    search_queries: string[];
    location?: string;
    max_price?: number;
    min_price?: number;
    categories?: string[];
    max_pages: number;
    delay_min_ms: number;
    delay_max_ms: number;
    use_proxy: boolean;
    proxy_list?: string[];
    headless: boolean;
    user_agent?: string;
    cookies?: any[];
    auth_credentials?: {
        email: string;
        password: string;
    };
}
export interface ScraperResult {
    marketplace: string;
    success: boolean;
    listings: ScrapedListing[];
    total_scraped: number;
    errors: string[];
    started_at: string;
    completed_at: string;
    duration_ms: number;
}
export type { ScraperHealthMetrics } from "@magnus-flipper-ai/core/types/scraper";
//# sourceMappingURL=ScrapedListing.d.ts.map