#!/bin/bash
# Magnus Environment Sync Script
# Ensures API → Web → Mobile have consistent environment variables

set -e

REPO_ROOT="/Users/chinyeosemene/Developer/Magnus-Flipper-AI-v1.0-pro"

echo "🔄 Magnus Environment Sync"
echo "=========================="
echo ""

# Check if production env exists
if [ ! -f "$REPO_ROOT/.env.production" ]; then
  echo "⚠️  .env.production not found. Creating from template..."
  cp "$REPO_ROOT/.env.production.template" "$REPO_ROOT/.env.production"
  echo "✅ Created .env.production (please fill in your values)"
  echo ""
fi

# Load production env
set -a
source "$REPO_ROOT/.env.production" 2>/dev/null || true
set +a

# Sync to Web
echo "📦 Syncing to web/.env.production..."
cat > "$REPO_ROOT/web/.env.production" <<EOF
# Auto-generated by env-sync.sh
# Last sync: $(date)

NEXT_PUBLIC_API_URL=${API_URL:-https://api.magnus-flipper.com}
NEXT_PUBLIC_SOCKET_URL=${API_URL:-https://api.magnus-flipper.com}
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL:-}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
NEXT_PUBLIC_APP_NAME=Magnus Flipper
NEXT_PUBLIC_APP_VERSION=1.0.0
NEXT_PUBLIC_ENV=production
NEXT_PUBLIC_ENABLE_ANALYTICS=true
NEXT_PUBLIC_ASSET_CDN=${ASSET_CDN:-}
EOF
echo "✅ Web environment synced"

# Sync to Mobile
echo "📱 Syncing to mobile/.env.production..."
cat > "$REPO_ROOT/mobile/.env.production" <<EOF
# Auto-generated by env-sync.sh
# Last sync: $(date)

EXPO_PUBLIC_API_URL=${API_URL:-https://api.magnus-flipper.com}
EXPO_PUBLIC_SOCKET_URL=${API_URL:-https://api.magnus-flipper.com}
EXPO_PUBLIC_SUPABASE_URL=${SUPABASE_URL:-}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY:-}
EXPO_PUBLIC_ENV=production
EXPO_PUBLIC_APP_NAME=Magnus Flipper AI
EXPO_PUBLIC_VERSION=1.0.0
EXPO_PUBLIC_REGION=us-east-1
EXPO_PUBLIC_BUILD_CHANNEL=production
EXPO_PUBLIC_RELEASE_CHANNEL=production
EXPO_PUBLIC_APP_MODE=production
EXPO_PUBLIC_ASSET_CDN=${ASSET_CDN:-}
EOF
echo "✅ Mobile environment synced"

echo ""
echo "✅ Environment sync complete!"
echo ""
echo "Synced values:"
echo "  API_URL: ${API_URL:-[not set]}"
echo "  SUPABASE_URL: ${SUPABASE_URL:-[not set]}"
echo "  STRIPE_KEY: ${STRIPE_PUBLISHABLE_KEY:+[set]}${STRIPE_PUBLISHABLE_KEY:-[not set]}"
echo ""
echo "⚠️  Remember to set these in Vercel dashboard:"
echo "  - NEXT_PUBLIC_API_URL"
echo "  - NEXT_PUBLIC_SUPABASE_URL"
echo "  - NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo ""
