#!/usr/bin/env node
/**
 * DeployGuardian GitHub Step Summary Renderer
 * 
 * Converts DeployGuardian JSON output into a GitHub Step Summary markdown.
 * This creates a rich, readable summary in the GitHub Actions UI.
 * 
 * Usage:
 *   node deployguardian_render_summary.js <path-to-json> [--output <file>]
 * 
 * If no --output is specified, writes to stdout (for piping to $GITHUB_STEP_SUMMARY)
 */

const fs = require("fs");
const path = require("path");

// Parse arguments
function parseArgs() {
  const args = process.argv.slice(2);
  const parsed = {
    input: null,
    output: null,
  };

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--output" || args[i] === "-o") {
      parsed.output = args[i + 1];
      i++;
    } else if (!parsed.input) {
      parsed.input = args[i];
    }
  }

  return parsed;
}

// Render markdown summary
function renderSummary(output) {
  const lines = [];

  // Title
  lines.push("## 🛡️ DeployGuardian v2 Validation Report");
  lines.push("");

  // Verdict badge
  const verdictEmoji = output.verdict.status === "SAFE" ? "✅" : "❌";
  const verdictText = output.verdict.status === "SAFE" ? "SAFE TO DEPLOY" : "UNSAFE TO DEPLOY";
  const verdictColor = output.verdict.status === "SAFE" ? "🟢" : "🔴";
  
  lines.push(`### ${verdictEmoji} Deployment Safety: **${verdictText}**`);
  lines.push("");

  // Metadata
  lines.push("**Validation Metadata:**");
  lines.push(`- **Mode:** \`${output.context.mode}\``);
  lines.push(`- **Branch:** \`${output.context.branch}\``);
  lines.push(`- **Actor:** @${output.context.actor}`);
  lines.push(`- **Commit:** \`${output.tool.commitSha.substring(0, 7)}\``);
  lines.push(`- **Duration:** ${(output.verdict.durationMs / 1000).toFixed(2)}s`);
  lines.push("");

  // Verdict summary
  lines.push("**Verdict Summary:**");
  lines.push(`- ${verdictColor} **Status:** ${output.verdict.status}`);
  lines.push(`- ❌ **Blockers:** ${output.verdict.blockers}`);
  lines.push(`- ⚠️  **Warnings:** ${output.verdict.warnings}`);
  lines.push(`- ✅ **Passed:** ${output.verdict.passed}`);
  lines.push("");

  // Checks table
  lines.push("### Validation Checks");
  lines.push("");
  lines.push("| Check | Status | Severity | Duration |");
  lines.push("|-------|--------|----------|----------|");

  for (const check of output.checks) {
    const statusIcon = check.status === "PASS" ? "✅" :
                       check.status === "FAIL" ? "❌" :
                       check.status === "WARN" ? "⚠️" : "⏭️";
    
    const severityBadge = check.severity === "BLOCKER" ? "🔴 BLOCKER" :
                          check.severity === "WARNING" ? "⚠️ WARNING" : "ℹ️ INFO";
    
    const duration = `${check.durationMs}ms`;
    
    lines.push(`| ${check.title} | ${statusIcon} ${check.status} | ${severityBadge} | ${duration} |`);
  }
  
  lines.push("");

  // Detailed check messages (only for non-PASS)
  const failedOrWarnedChecks = output.checks.filter(c => c.status !== "PASS");
  
  if (failedOrWarnedChecks.length > 0) {
    lines.push("### Detailed Results");
    lines.push("");

    for (const check of failedOrWarnedChecks) {
      const icon = check.status === "FAIL" ? "❌" : "⚠️";
      lines.push(`#### ${icon} ${check.title}`);
      lines.push("");
      lines.push(`**Status:** ${check.status} (${check.severity})`);
      lines.push(`**Summary:** ${check.humanSummary}`);
      lines.push("");

      if (check.messages && check.messages.length > 0) {
        lines.push("**Messages:**");
        for (const msg of check.messages) {
          const msgIcon = msg.severity === "BLOCKER" ? "❌" :
                         msg.severity === "WARNING" ? "⚠️" : "ℹ️";
          lines.push(`- ${msgIcon} ${msg.text}`);
        }
        lines.push("");
      }
    }
  }

  // Action items
  if (output.verdict.status === "UNSAFE") {
    lines.push("### 🚨 Action Required");
    lines.push("");
    lines.push(`**Deployment is blocked due to ${output.verdict.blockers} blocker(s).**`);
    lines.push("");
    lines.push("Please fix the following issues before deploying:");
    lines.push("");

    const blockerChecks = output.checks.filter(c => 
      c.messages && c.messages.some(m => m.severity === "BLOCKER")
    );

    for (const check of blockerChecks) {
      lines.push(`- **${check.title}**: ${check.humanSummary}`);
    }
    lines.push("");
  } else if (output.verdict.warnings > 0) {
    lines.push("### ⚠️ Warnings");
    lines.push("");
    lines.push(`**Deployment is SAFE but has ${output.verdict.warnings} warning(s).**`);
    lines.push("");
    lines.push("Consider addressing the following warnings:");
    lines.push("");

    const warningChecks = output.checks.filter(c => 
      c.status === "WARN" || (c.messages && c.messages.some(m => m.severity === "WARNING"))
    );

    for (const check of warningChecks) {
      lines.push(`- **${check.title}**: ${check.humanSummary}`);
    }
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push(`*Generated by DeployGuardian v${output.tool.version} on ${new Date(output.tool.timestamp).toLocaleString()}*`);
  lines.push("");

  return lines.join("\n");
}

// Main execution
function main() {
  const args = parseArgs();

  if (!args.input) {
    console.error("Usage: node deployguardian_render_summary.js <path-to-json> [--output <file>]");
    console.error("");
    console.error("Example:");
    console.error("  node deployguardian_render_summary.js artifacts/deployguardian.json");
    console.error("  node deployguardian_render_summary.js artifacts/deployguardian.json --output summary.md");
    console.error("  node deployguardian_render_summary.js artifacts/deployguardian.json >> $GITHUB_STEP_SUMMARY");
    process.exit(1);
  }

  // Check if input file exists
  if (!fs.existsSync(args.input)) {
    console.error(`Error: Input file not found: ${args.input}`);
    process.exit(1);
  }

  // Load JSON
  let output;
  try {
    const content = fs.readFileSync(args.input, "utf8");
    output = JSON.parse(content);
  } catch (err) {
    console.error(`Error: Failed to parse JSON: ${err.message}`);
    process.exit(1);
  }

  // Validate contract version
  if (!output.contractVersion || !output.contractVersion.startsWith("2.")) {
    console.error(`Error: Invalid or unsupported contract version: ${output.contractVersion}`);
    process.exit(1);
  }

  // Render summary
  const markdown = renderSummary(output);

  // Output
  if (args.output) {
    fs.writeFileSync(args.output, markdown, "utf8");
    console.log(`✅ Summary written to: ${args.output}`);
  } else {
    console.log(markdown);
  }
}

if (require.main === module) {
  try {
    main();
  } catch (err) {
    console.error(`Error: ${err.message}`);
    console.error(err.stack);
    process.exit(2);
  }
}

module.exports = { renderSummary };
