import type { Listing, SavedSearch } from "@magnus-flipper-ai/core";

export const DEMO_SEARCHES: SavedSearch[] = [
  {
    id: "demo-1",
    userId: "demo",
    name: "NYC iPhone flips",
    category: "Phones",
    manufacturer: "Apple",
    models: ["iPhone 14 Pro", "iPhone 15"],
    minPrice: 300,
    maxPrice: 900,
    radiusMiles: 25,
    conditions: ["GOOD"],
    sites: ["FB_MARKETPLACE", "CRAIGSLIST"],
    maxResultsPerRun: 20,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-2",
    userId: "demo",
    name: "LA couches under $300",
    category: "Couches",
    minPrice: 50,
    maxPrice: 300,
    radiusMiles: 20,
    conditions: ["GOOD", "LIKE_NEW"],
    sites: ["FB_MARKETPLACE", "OFFERUP"],
    maxResultsPerRun: 15,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEMO_ALERTS = [
  {
    id: "alert-1",
    savedSearchId: "demo-1",
    listingId: "listing-1",
    matchedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    notified: true,
    listing: {
      site: "FB_MARKETPLACE",
      city: "Brooklyn",
    },
  },
  {
    id: "alert-2",
    savedSearchId: "demo-2",
    listingId: "listing-2",
    matchedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    notified: true,
    listing: {
      site: "OFFERUP",
      city: "Los Angeles",
    },
  },
];

export const DEMO_LISTINGS: Listing[] = [
  {
    id: "listing-1",
    externalId: "ext-1",
    site: "FB_MARKETPLACE",
    url: "#",
    title: "iPhone 14 Pro Max - Unlocked - Great Condition",
    price: 750,
    currency: "USD",
    manufacturer: "Apple",
    model: "iPhone 14 Pro Max",
    condition: "GOOD",
    city: "Brooklyn",
    scrapedAt: new Date().toISOString(),
    postedAt: new Date().toISOString(),
    imageUrls: [],
  },
  {
    id: "listing-2",
    externalId: "ext-2",
    site: "OFFERUP",
    url: "#",
    title: "West Elm Sectional Sofa - Light Gray",
    price: 450,
    currency: "USD",
    condition: "LIKE_NEW",
    city: "Los Angeles",
    scrapedAt: new Date().toISOString(),
    postedAt: new Date().toISOString(),
    imageUrls: [],
  },
  {
    id: "listing-3",
    externalId: "ext-3",
    site: "CRAIGSLIST",
    url: "#",
    title: "2015 Toyota Corolla LE - 92k miles",
    price: 9800,
    currency: "USD",
    manufacturer: "Toyota",
    model: "Corolla",
    condition: "GOOD",
    city: "Queens",
    scrapedAt: new Date().toISOString(),
    postedAt: new Date().toISOString(),
    imageUrls: [],
  },
];
