import type { SavedSearch } from "@magnus-flipper-ai/core";

export const DEMO_SAVED_SEARCHES: SavedSearch[] = [
  {
    id: "demo-s1",
    userId: "demo",
    name: "Starter Phone Deals",
    category: "Phones",
    manufacturer: "Apple",
    minPrice: 200,
    maxPrice: 800,
    radiusMiles: 30,
    maxResultsPerRun: 20,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditions: ["GOOD"],
    models: ["iPhone 12", "iPhone 13"],
    sites: ["FB_MARKETPLACE"],
  },
  {
    id: "demo-s2",
    userId: "demo",
    name: "Weekend Couch Hunt",
    category: "Couches",
    minPrice: 50,
    maxPrice: 400,
    radiusMiles: 15,
    maxResultsPerRun: 15,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    conditions: ["GOOD", "LIKE_NEW"],
    models: [],
    sites: ["OFFERUP", "FB_MARKETPLACE"],
  },
];
